spring.application.name=UserService
server.port=8085
#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/userservice_db
spring.datasource.username=root
spring.datasource.password=srinivasH53@
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver


#log
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG


#Flyway
spring.flyway.baseline-version=1
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true
#JPA configuration
spring.jpa.hibernate.ddl-auto=validate

##Eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Api Docs
springdoc.api-docs.path=/user-service/v3/api-docs
springdoc.swagger-ui.path=/user-service/swagger-ui
